name: JohnAIController
version: 6.0.0
main: me.cliff.johnaicontroller.JohnAIControllerPlugin
api-version: '1.20'
depend: [Citizens]

commands:
  john:
    description: Control NPC John
    usage: /john <inv|pickup|drop|equip|offhand|use|say>
    permission: johnaicontroller.use

permissions:
  johnaicontroller.use:
    default: op
